# Generated by Django 2.1.3 on 2018-11-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_personaje_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='consola',
            field=models.CharField(default='default.png', max_length=60),
        ),
        migrations.AddField(
            model_name='personaje',
            name='compania',
            field=models.CharField(default='default.png', max_length=30),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(default='default.png', max_length=30),
        ),
    ]
